#!/bin/bash

queryApp() {
  dbus-send --session --type=method_call \
    --dest=com.juminai.Apps \
    /com/juminai/Apps \
    com.juminai.Apps.Query \
    string:$1
}

updateFreq() {
  dbus-send --session --type=method_call \
    --dest=com.juminai.Apps \
    /com/juminai/Apps \
    com.juminai.Apps.UpdateFreq \
    string:$1
}

add() {
  dbus-send --session --type=method_call \
    --dest=com.juminai.Apps \
    /com/juminai/Apps \
    com.juminai.Apps.Add\
    string:$1
}

if [[ $1 == 'query' ]]; then queryApp $2; fi
if [[ $1 == 'freq' ]]; then updateFreq $2; fi
if [[ $1 == 'add' ]]; then add $2; fi
